export const SET_FORM_BRAND_NAME = 'SET_FORM_BRAND_NAME';
export const REQUEST_BRANDS = 'REQUEST_BRANDS';
export const REQUEST_BRAND = 'REQUEST_BRAND';
export const RECEIVE_BRANDS = 'RECEIVE_BRANDS';
export const RECEIVE_BRAND = 'RECEIVE_BRAND';
export const RECEIVE_ERRORS = 'RECEIVE_ERRORS';
export const POST_BRAND = 'POST_BRAND';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const DELETE_BRAND = 'DELETE_BRAND';

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const POST_PRODUCT = 'POST_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_BRAND';

export const COMPLETE_UPDATE = 'COMPLETE_UPDATE';
